//! Autostart on login via a systemd user unit
//! (`~/.config/systemd/user/mixweave.service`). The unit is anchored to
//! `graphical-session.target` so it starts with the desktop session (which
//! also provides the WAYLAND_DISPLAY/DISPLAY environment) and after
//! PipeWire is up.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

use crate::error::SinkError;

static AUTOSTART_OPERATION: std::sync::Mutex<()> = std::sync::Mutex::new(());

const UNIT_NAME: &str = "mixweave.service";
/// Unit names used by past app names, oldest last - checked whenever we need
/// to find or clean up whatever an existing install already has enabled.
const LEGACY_UNIT_NAMES: &[&str] = &["sonux.service", "sink.service"];

fn named_unit_path(name: &str) -> Result<PathBuf, SinkError> {
    let dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    Ok(dir.join("systemd").join("user").join(name))
}

fn unit_path() -> Result<PathBuf, SinkError> {
    named_unit_path(UNIT_NAME)
}

fn render_unit() -> Result<String, SinkError> {
    let exe = crate::launch_path::launch_path()
        .map_err(|e| SinkError::Config(format!("cannot resolve own executable path: {e}")))?;
    // Quote for systemd's unit syntax so paths with spaces (or quotes -
    // however unlikely) don't split into command + arguments.
    let exe = format!(
        "\"{}\"",
        exe.display()
            .to_string()
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
    );
    // Boot to tray on login when the user asked for it. Only the autostart
    // launch carries this flag, so manual launches still show the window.
    let exe = if crate::persistence::prefs::Prefs::load().start_minimized {
        format!("{exe} --minimized")
    } else {
        exe
    };
    Ok(format!(
        "# Generated by Mixweave. Re-enabling autostart rewrites this file,\n\
         # so the path tracks wherever the binary currently lives.\n\
         [Unit]\n\
         Description=Mixweave audio mixer\n\
         After=graphical-session.target pipewire.service wireplumber.service\n\
         PartOf=graphical-session.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart={}\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         \n\
         [Install]\n\
         WantedBy=graphical-session.target\n",
        exe
    ))
}

fn systemctl(args: &[&str]) -> Result<std::process::Output, SinkError> {
    Command::new("systemctl")
        .arg("--user")
        .args(args)
        .output()
        .map_err(|e| SinkError::Config(format!("systemctl --user {}: {e}", args.join(" "))))
}

pub fn is_enabled() -> bool {
    systemctl(&["is-enabled", UNIT_NAME])
        .map(|out| out.status.success())
        .unwrap_or(false)
        || LEGACY_UNIT_NAMES.iter().any(|name| {
            systemctl(&["is-enabled", name])
                .map(|out| out.status.success())
                .unwrap_or(false)
        })
}

/// Replace an enabled pre-Mixweave service with the current unit without
/// leaving an autostart gap. Stale, disabled legacy unit files are removed
/// as well.
pub fn migrate_legacy_unit() -> Result<(), SinkError> {
    for legacy_name in LEGACY_UNIT_NAMES {
        let legacy_path = named_unit_path(legacy_name)?;
        let legacy_enabled = systemctl(&["is-enabled", legacy_name])
            .map(|out| out.status.success())
            .unwrap_or(false);
        if !legacy_enabled && !legacy_path.exists() {
            continue;
        }
        if legacy_enabled {
            enable()?;
        }
        let _ = systemctl(&["disable", legacy_name]);
        if legacy_path.exists() {
            super::remove_file(&legacy_path)?;
        }
    }
    let _ = systemctl(&["daemon-reload"]);
    Ok(())
}

pub fn enable() -> Result<(), SinkError> {
    // A development build loads the Vite dev server, which is not running at
    // login: the autostarted window would only show a connection error.
    if cfg!(debug_assertions) {
        return Err(SinkError::Config(
            "Start at login is not available in a development build - its window needs the \
             dev server. Enable it from the installed or AppImage build."
                .into(),
        ));
    }
    let _config_write = super::begin_config_write()?;
    let _operation = AUTOSTART_OPERATION
        .lock()
        .map_err(|_| SinkError::Config("autostart operation lock poisoned".into()))?;
    let path = unit_path()?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    crate::persistence::write_atomic(&path, render_unit()?)?;

    for step in [&["daemon-reload"][..], &["enable", UNIT_NAME][..]] {
        let out = systemctl(step)?;
        if !out.status.success() {
            return Err(SinkError::Config(format!(
                "systemctl --user {} failed: {}",
                step.join(" "),
                String::from_utf8_lossy(&out.stderr).trim()
            )));
        }
    }
    Ok(())
}

pub fn disable() -> Result<(), SinkError> {
    let _config_write = super::begin_config_write()?;
    let _operation = AUTOSTART_OPERATION
        .lock()
        .map_err(|_| SinkError::Config("autostart operation lock poisoned".into()))?;
    let out = systemctl(&["disable", UNIT_NAME])?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        // Disabling a unit that was never enabled is fine.
        if !stderr.contains("does not exist") {
            return Err(SinkError::Config(format!(
                "systemctl --user disable failed: {}",
                stderr.trim()
            )));
        }
    }
    let path = unit_path()?;
    if path.exists() {
        super::remove_file(&path)?;
    }
    for legacy_name in LEGACY_UNIT_NAMES {
        let _ = systemctl(&["disable", legacy_name]);
        let legacy_path = named_unit_path(legacy_name)?;
        if legacy_path.exists() {
            super::remove_file(&legacy_path)?;
        }
    }
    let _ = systemctl(&["daemon-reload"]);
    Ok(())
}
