//! WirePlumber 0.5+ integration for routing application streams before their
//! first link is created.
//!
//! A fixed Lua policy hook is installed in WirePlumber's user data directory
//! and enabled by a configuration fragment. The hook reads the current route
//! map from the `sonux.routes.v1` key on subject 0 of WirePlumber's `default`
//! metadata object. Assignment changes therefore do not require a WirePlumber
//! restart; only installing the hook for the first time does.

use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::error::SinkError;
use crate::persistence::assignments::{Assignment, Assignments};
use crate::persistence::seen::SeenApps;

pub const ROUTES_METADATA_KEY: &str = "sonux.routes.v1";
pub const ROUTES_METADATA_TYPE: &str = "Spa:String:JSON";
pub const ROUTES_ACK_METADATA_KEY: &str = "sonux.routes.ack.v1";
pub const ROUTES_READY_METADATA_KEY: &str = "sonux.routes.ready.v1";
pub const ROUTES_CLEAR_ACK: &str = "cleared";

const COMPONENT_CONF: &str = r#"# Generated by Mixweave (audio mixer). Do not edit.
wireplumber.components = [
  {
    name = mixweave-routing.lua, type = script/lua
    provides = hooks.mixweave.routing
    requires = [ metadata.default, policy.linking.standard ]
  }
]

wireplumber.profiles = {
  main = {
    hooks.mixweave.routing = required
  }
}
"#;

const ROUTING_SCRIPT: &str = include_str!("../../assets/wireplumber/mixweave-routing.lua");

#[derive(Serialize)]
struct RoutesMetadata<'a> {
    version: u8,
    routes: Vec<&'a Assignment>,
}

pub fn routes_metadata_value(
    assignments: &Assignments,
    seen: &SeenApps,
) -> Result<String, SinkError> {
    serde_json::to_string(&RoutesMetadata {
        version: 1,
        routes: assignments
            .assignments
            .iter()
            .filter(|route| !seen.is_ignored(&route.match_prop, &route.match_value))
            .collect(),
    })
    .map_err(|error| SinkError::Config(format!("serialize WirePlumber routes: {error}")))
}

fn named_conf_path(config_dir: &Path, name: &str) -> PathBuf {
    config_dir
        .join("wireplumber")
        .join("wireplumber.conf.d")
        .join(name)
}

fn conf_path_from(config_dir: &Path) -> PathBuf {
    named_conf_path(config_dir, "90-mixweave-routing.conf")
}

fn script_path_from(data_dir: &Path) -> PathBuf {
    data_dir
        .join("wireplumber")
        .join("scripts")
        .join("mixweave-routing.lua")
}

fn legacy_script_path_from(data_dir: &Path, name: &str) -> PathBuf {
    data_dir.join("wireplumber").join("scripts").join(name)
}

pub fn conf_path() -> Result<PathBuf, SinkError> {
    let dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    Ok(conf_path_from(&dir))
}

pub fn script_path() -> Result<PathBuf, SinkError> {
    let dir = dirs::data_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user data directory".into()))?;
    Ok(script_path_from(&dir))
}

fn install_at(config_dir: &Path, data_dir: &Path) -> Result<(), SinkError> {
    let script = script_path_from(data_dir);
    if let Some(parent) = script.parent() {
        super::ensure_private_dir(parent)?;
    }
    // Install the dependency first. A failed second write can leave an unused
    // script, but never a component that points at a missing script.
    super::write_atomic(&script, ROUTING_SCRIPT)?;

    let conf = conf_path_from(config_dir);
    if let Some(parent) = conf.parent() {
        super::ensure_private_dir(parent)?;
    }
    super::write_atomic(&conf, COMPONENT_CONF)?;
    Ok(())
}

fn migrate_at(config_dir: &Path, data_dir: &Path) -> Result<(), SinkError> {
    install_at(config_dir, data_dir)?;
    // Sink-era: the legacy generated `stream.rules` fragment.
    let legacy_conf = named_conf_path(config_dir, "90-sink-routing.conf");
    if legacy_conf.exists() {
        super::remove_file(&legacy_conf)?;
    }
    // Sonux-era: same fixed-component scheme as today, under the old
    // filenames. Left in place, its component would stay `required` and
    // run its hooks a second time alongside the current one.
    let legacy_sonux_conf = named_conf_path(config_dir, "90-sonux-routing.conf");
    if legacy_sonux_conf.exists() {
        super::remove_file(&legacy_sonux_conf)?;
    }
    let legacy_sonux_script = legacy_script_path_from(data_dir, "sonux-routing.lua");
    if legacy_sonux_script.exists() {
        super::remove_file(&legacy_sonux_script)?;
    }
    Ok(())
}

/// Replace whatever an older app name last installed - the legacy generated
/// `stream.rules` fragment, or a previous rename's copy of this same fixed
/// policy component - with the current one, after installation succeeds.
pub fn migrate_legacy_conf() -> Result<(), SinkError> {
    let config_dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    let data_dir = dirs::data_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user data directory".into()))?;
    migrate_at(&config_dir, &data_dir)
}

/// Ensure the fixed WirePlumber integration is installed. The route map itself
/// is published through PipeWire metadata by the audio backend; it is not
/// rendered into this startup-only configuration.
pub fn write(_assignments: &Assignments) -> Result<(), SinkError> {
    let config_dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    let data_dir = dirs::data_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user data directory".into()))?;
    install_at(&config_dir, &data_dir)
}

/// Remove both files owned by this integration. Missing files are harmless so
/// factory reset can be retried after a partial cleanup.
pub fn remove_installation() -> Result<(), SinkError> {
    for path in [conf_path()?, script_path()?] {
        if path.exists() {
            super::remove_file(&path)?;
        }
    }
    Ok(())
}
